function sys=homing_ldm_aggiornatref
sys = [];
sys.child = [];
sys.NumDataTypes = 5; 
sys.DataTypes = [];
temp.EnumNames='';
temp.EnumValues = [];
temp.Name = '';
sys.DataTypes = repmat(temp,1,5);
sys.DataTypes(1).Name = 'real_T';
sys.DataTypes(2).Name = 'struct_p4a3fbOfYyoF57AQ0TsR2D';
sys.DataTypes(3).Name = 'struct_MxqrZmnGbOcHrCh1hlquB';
sys.DataTypes(4).Name = 'creal_T';
sys.DataTypes(5).Name = 'struct_0cTP9OGKNIwjZ53OR7EfCC';
